### ISSUE TITLE
Gestión de Materiales de Estudio

### ISSUE THREAD

**Issue by kanye1803** [uptagprojects/cartelera-cms#12]
Permitir a los profesores subir y organizar diversos tipos de materiales de estudio (documentos, presentaciones, videos) en una estructura de carpetas.

Criterio de aceptación: Los materiales deben poder ser descargados por los estudiantes.

Consideraciones: Implementar un sistema de búsqueda eficiente para que los estudiantes encuentren fácilmente los materiales.

**Comment by ginniecodes** [comment]
Showing the attachments in a folder accordion or structure are not in our designs. We will look at this feature.
This is a great issue, thank you. Let me split some of them:
- Attachments should be downloaded. Everything except YouTube videos can be downloaded.
- Include a search bar on top of the navigation.
- Support searching throughout the content of our attachments.
