### ISSUE TITLE
Implementar la edición de contenido publicado

### ISSUE THREAD

**Issue by kanye1803** [uptagprojects/cartelera-cms#15]
Permitir a los profesores modificar el texto, imágenes y otros elementos de un contenido publicado después de su creación.

Criterios de aceptación: El profesor puede acceder a un formulario de edición para modificar el contenido.

Consideracion: Los cambios realizados deben reflejarse inmediatamente en la vista del contenido.

**Comment by ginniecodes** [comment]
Split this issue into small features:
- create a guide draft
- publish drafts
- support inline images inside guides
- support uploading documents into our Dropbox
- create domain events for guide actions (new guide created, guide deleted, guide published, etc)
